apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  GITHUB_TOKEN: '' # Add your GitHub token here or use external secrets manager
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: backstage-password-change-me
